# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 09:29
from __future__ import unicode_literals

from django.db import migrations

import requests

REDMINE_APIS = ['https://redmine.laas.fr', 'https://git.openrobots.org']

def redmine(apps, schema_editor):
    Project, License, Package, Repo = (apps.get_model('gepetto_packages', model)
                                       for model in ['Project', 'License', 'Package', 'Repo'])
    for api in REDMINE_APIS:
        for data in requests.get(f'{api}/projects.json?limit=100').json()['projects']:
            package_qs = Package.objects.filter(name=data['name'])
            if package_qs.exists():
                r = Repo(package=package_qs.first(), repo_id=data['id'])
                r.homepage = requests.get(f'{api}/projects/{r.repo_id}.json').json()['project']['homepage']
                r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gepetto_packages', '0003_gitlab'),
    ]

    operations = [
    ]
