variables:
  GIT_SSL_NO_VERIFY: "true"

dashboard:
  stage: deploy
  image: eur0c.laas.fr:4567/stack-of-tasks/pinocchio-tutorials/deploy
  before_script:
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts
  script: "ssh -p 222 web@eur0c ./deploy-dashboard.sh"

