#!/usr/bin/env python3

import re
from pathlib import Path

from bibtexparser import load, loads
from bibtexparser.bibdatabase import BibDatabase
from requests import get


HAL_RE = [
    (re.compile(r'(hal|tel|inria|lirmm)-\d{8}?', re.I),
     lambda g: g),
    (re.compile(r'/\d\d/\d\d/\d\d/\d\d/'),
     lambda g: 'hal-%08i' % int(g.replace('/', ''))),
]
HAL_KEYS = ['url', 'link', 'pdf', 'video']
USELESS_KEYS = {'hal_local_reference', 'hal_version', 'address', 'note', 'month'}


def parse_hal_id(entry):
    """ Tries to find HAL_ID in an entry"""
    if 'hal_id' in entry:
        return entry['hal_id']
    for regex, ret in HAL_RE:
        for key in HAL_KEYS:
            if key in entry:
                match = regex.search(entry[key])
                if match:
                    return ret(match.group())

def get_hal_entry(hal_id, hal_db):
    """ Get the entry of HAL_ID as generated by HAL. Tries local then online """
    for key in hal_db.entries_dict.keys():
        if key.endswith(hal_id):
            return hal_db.entries_dict[key]
    url = 'https://hal.archives-ouvertes.fr/%s/bibtex' % hal_id
    r = get(url)
    r.raise_for_status()
    if 'Aucun document trouvé' in r.content.decode():
        print('fail on %s' % url)
    hal_entry = loads(r.content.decode()).entries[0]
    print('HAL_ENTRY for {ID} ({hal_id}) not found on local hal db. Got Online one.'.format(**hal_entry))
    return hal_entry


def check_hal(entry, hal_db):
    """ Checks our DB is update with HAL """
    hal_id = parse_hal_id(entry)
    if not hal_id:
        return
    hal_entry = get_hal_entry(hal_id, hal_db)
    keys = (set(entry.keys()) | set(hal_entry.keys())) - USELESS_KEYS
    for key in keys:
        if key not in entry:
            print('IN HAL for %s: %s = {%s},' % (entry['ID'], key, hal_entry[key]))


if __name__ == '__main__':
    with open('hal.bib') as hal_file:
        hal_db = load(hal_file)
    for path in Path('bib').glob('*.bib'):
        print('==== {:^15} ===='.format(path.name))
        with path.open() as f:
            db = load(f)
        for entry in db.entries:
            check_hal(entry, hal_db)
