# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 15:55
from __future__ import unicode_literals

import os

from django.db import migrations

import requests

from gepetto_packages.utils import SOURCES, api_headers, api_data

GITHUB_API = 'https://api.github.com'
GITHUB_TOKEN = os.getenv('GITHUB_TOKEN', '')
HEADERS = api_headers(source=SOURCES.github, token=GITHUB_TOKEN)
PROJECTS = (
    'Humanoid Path Planner',
    'Stack of Tasks'
)

def github_licenses(apps, schema_editor):
    License = apps.get_model('gepetto_packages', 'License')
    for data in requests.get(f'{GITHUB_API}/licenses', headers=HEADERS).json():
        License.objects.create(github_key=data['key'], **{key: data[key] for key in ['name', 'spdx_id', 'url']})


def github_projects(apps, schema_editor):
    Project, License, Package, Repo = (apps.get_model('gepetto_packages', model)
                                       for model in ['Project', 'License', 'Package', 'Repo'])
    for project_name in PROJECTS:
        project = Project.objects.create(name=project_name)
        for data in requests.get(f'{GITHUB_API}/orgs/{project.slug}/repos', headers=HEADERS).json():
            package = Package.objects.create(name=data['name'], project=project, homepage=data['homepage'])
            repo = Repo.objects.create(package=package, url=data['html_url'], homepage=data['homepage'],
                                       repo_id=data['id'], default_branch=data['default_branch'],
                                       open_issues=data['open_issues'], source_type=SOURCES.github,
                                       api_url=GITHUB_API, token=GITHUB_TOKEN)
            repo_data = api_data(repo)
            if 'license' in repo_data and repo_data['license']:
                license_data = repo_data['license']
                license, _ = License.objects.get_or_create(github_key=license_data['key'], name=license_data['name'])
                repo.license = license
                package.license = license
                package.save()
            repo.open_pr = len(api_data(repo, '/pulls'))
            repo.save()

class Migration(migrations.Migration):

    dependencies = [
        ('gepetto_packages', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(github_licenses),
        migrations.RunPython(github_projects),
    ]
